/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FamilyRouteImport } from './routes/_family'
import { Route as StaffRouteImport } from './routes/_staff'
import { Route as FamilyLoginRouteImport } from './routes/family-login'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FamilyMeRouteImport } from './routes/_family/me'
import { Route as StaffIndexRouteImport } from './routes/_staff/index'
import { Route as StaffAuditRouteImport } from './routes/_staff/audit'
import { Route as StaffDashboardRouteImport } from './routes/_staff/dashboard'
import { Route as StaffLookupsRouteImport } from './routes/_staff/lookups'
import { Route as StaffMembersRouteImport } from './routes/_staff/members'
import { Route as StaffReportsRouteImport } from './routes/_staff/reports'
import { Route as StaffUpdateRequestsRouteImport } from './routes/_staff/update-requests'
import { Route as StaffUsersRouteImport } from './routes/_staff/users'
import { Route as StaffFamiliesIndexRouteImport } from './routes/_staff/families/index'
import { Route as StaffFamiliesIdRouteImport } from './routes/_staff/families/$id'
import { Route as StaffFamiliesNewRouteImport } from './routes/_staff/families/new'

const FamilyRoute = FamilyRouteImport.update({
  id: '/_family',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/_staff',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyLoginRoute = FamilyLoginRouteImport.update({
  id: '/family-login',
  path: '/family-login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyMeRoute = FamilyMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => FamilyRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAuditRoute = StaffAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StaffRoute,
} as any)
const StaffLookupsRoute = StaffLookupsRouteImport.update({
  id: '/lookups',
  path: '/lookups',
  getParentRoute: () => StaffRoute,
} as any)
const StaffMembersRoute = StaffMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => StaffRoute,
} as any)
const StaffReportsRoute = StaffReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => StaffRoute,
} as any)
const StaffUpdateRequestsRoute = StaffUpdateRequestsRouteImport.update({
  id: '/update-requests',
  path: '/update-requests',
  getParentRoute: () => StaffRoute,
} as any)
const StaffUsersRoute = StaffUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFamiliesIndexRoute = StaffFamiliesIndexRouteImport.update({
  id: '/families/',
  path: '/families/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFamiliesIdRoute = StaffFamiliesIdRouteImport.update({
  id: '/families/$id',
  path: '/families/$id',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFamiliesNewRoute = StaffFamiliesNewRouteImport.update({
  id: '/families/new',
  path: '/families/new',
  getParentRoute: () => StaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StaffIndexRoute
  '/family-login': typeof FamilyLoginRoute
  '/login': typeof LoginRoute
  '/me': typeof FamilyMeRoute
  '/audit': typeof StaffAuditRoute
  '/dashboard': typeof StaffDashboardRoute
  '/lookups': typeof StaffLookupsRoute
  '/members': typeof StaffMembersRoute
  '/reports': typeof StaffReportsRoute
  '/update-requests': typeof StaffUpdateRequestsRoute
  '/users': typeof StaffUsersRoute
  '/families/$id': typeof StaffFamiliesIdRoute
  '/families/new': typeof StaffFamiliesNewRoute
  '/families/': typeof StaffFamiliesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof StaffIndexRoute
  '/family-login': typeof FamilyLoginRoute
  '/login': typeof LoginRoute
  '/me': typeof FamilyMeRoute
  '/audit': typeof StaffAuditRoute
  '/dashboard': typeof StaffDashboardRoute
  '/lookups': typeof StaffLookupsRoute
  '/members': typeof StaffMembersRoute
  '/reports': typeof StaffReportsRoute
  '/update-requests': typeof StaffUpdateRequestsRoute
  '/users': typeof StaffUsersRoute
  '/families/$id': typeof StaffFamiliesIdRoute
  '/families/new': typeof StaffFamiliesNewRoute
  '/families': typeof StaffFamiliesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_family': typeof FamilyRouteWithChildren
  '/_staff': typeof StaffRouteWithChildren
  '/family-login': typeof FamilyLoginRoute
  '/login': typeof LoginRoute
  '/_family/me': typeof FamilyMeRoute
  '/_staff/audit': typeof StaffAuditRoute
  '/_staff/dashboard': typeof StaffDashboardRoute
  '/_staff/lookups': typeof StaffLookupsRoute
  '/_staff/members': typeof StaffMembersRoute
  '/_staff/reports': typeof StaffReportsRoute
  '/_staff/update-requests': typeof StaffUpdateRequestsRoute
  '/_staff/users': typeof StaffUsersRoute
  '/_staff/': typeof StaffIndexRoute
  '/_staff/families/$id': typeof StaffFamiliesIdRoute
  '/_staff/families/new': typeof StaffFamiliesNewRoute
  '/_staff/families/': typeof StaffFamiliesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/family-login'
    | '/login'
    | '/me'
    | '/audit'
    | '/dashboard'
    | '/lookups'
    | '/members'
    | '/reports'
    | '/update-requests'
    | '/users'
    | '/families/$id'
    | '/families/new'
    | '/families/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/family-login'
    | '/login'
    | '/me'
    | '/audit'
    | '/dashboard'
    | '/lookups'
    | '/members'
    | '/reports'
    | '/update-requests'
    | '/users'
    | '/families/$id'
    | '/families/new'
    | '/families'
  id:
    | '__root__'
    | '/_family'
    | '/_staff'
    | '/family-login'
    | '/login'
    | '/_family/me'
    | '/_staff/audit'
    | '/_staff/dashboard'
    | '/_staff/lookups'
    | '/_staff/members'
    | '/_staff/reports'
    | '/_staff/update-requests'
    | '/_staff/users'
    | '/_staff/'
    | '/_staff/families/$id'
    | '/_staff/families/new'
    | '/_staff/families/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FamilyRoute: typeof FamilyRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  FamilyLoginRoute: typeof FamilyLoginRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_family': {
      id: '/_family'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff': {
      id: '/_staff'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-login': {
      id: '/family-login'
      path: '/family-login'
      fullPath: '/family-login'
      preLoaderRoute: typeof FamilyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_family/me': {
      id: '/_family/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof FamilyMeRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/_staff/': {
      id: '/_staff/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/audit': {
      id: '/_staff/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof StaffAuditRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/dashboard': {
      id: '/_staff/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/lookups': {
      id: '/_staff/lookups'
      path: '/lookups'
      fullPath: '/lookups'
      preLoaderRoute: typeof StaffLookupsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/members': {
      id: '/_staff/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof StaffMembersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/reports': {
      id: '/_staff/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof StaffReportsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/update-requests': {
      id: '/_staff/update-requests'
      path: '/update-requests'
      fullPath: '/update-requests'
      preLoaderRoute: typeof StaffUpdateRequestsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/users': {
      id: '/_staff/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof StaffUsersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/families/': {
      id: '/_staff/families/'
      path: '/families'
      fullPath: '/families/'
      preLoaderRoute: typeof StaffFamiliesIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/families/$id': {
      id: '/_staff/families/$id'
      path: '/families/$id'
      fullPath: '/families/$id'
      preLoaderRoute: typeof StaffFamiliesIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/families/new': {
      id: '/_staff/families/new'
      path: '/families/new'
      fullPath: '/families/new'
      preLoaderRoute: typeof StaffFamiliesNewRouteImport
      parentRoute: typeof StaffRoute
    }
  }
}

interface FamilyRouteChildren {
  FamilyMeRoute: typeof FamilyMeRoute
}

const FamilyRouteChildren: FamilyRouteChildren = {
  FamilyMeRoute: FamilyMeRoute,
}

const FamilyRouteWithChildren =
  FamilyRoute._addFileChildren(FamilyRouteChildren)

interface StaffRouteChildren {
  StaffAuditRoute: typeof StaffAuditRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffLookupsRoute: typeof StaffLookupsRoute
  StaffMembersRoute: typeof StaffMembersRoute
  StaffReportsRoute: typeof StaffReportsRoute
  StaffUpdateRequestsRoute: typeof StaffUpdateRequestsRoute
  StaffUsersRoute: typeof StaffUsersRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StaffFamiliesIdRoute: typeof StaffFamiliesIdRoute
  StaffFamiliesNewRoute: typeof StaffFamiliesNewRoute
  StaffFamiliesIndexRoute: typeof StaffFamiliesIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAuditRoute: StaffAuditRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffLookupsRoute: StaffLookupsRoute,
  StaffMembersRoute: StaffMembersRoute,
  StaffReportsRoute: StaffReportsRoute,
  StaffUpdateRequestsRoute: StaffUpdateRequestsRoute,
  StaffUsersRoute: StaffUsersRoute,
  StaffIndexRoute: StaffIndexRoute,
  StaffFamiliesIdRoute: StaffFamiliesIdRoute,
  StaffFamiliesNewRoute: StaffFamiliesNewRoute,
  StaffFamiliesIndexRoute: StaffFamiliesIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  FamilyRoute: FamilyRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  FamilyLoginRoute: FamilyLoginRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
